Module.add( 'dataStickers', ()=>{

let StickerList = Type.establish( 'Sticker', {}, {
	mmWall: { img: "terrain/wallProxy.png" },
	mmObserver: { img: "gems/Gem Type2 Yellow.png" },
	mmEnemy: { img: "gems/Gem Type2 Red.png" },
	mmFriend: { img: "gems/Gem Type2 Green.png" },
	mmGate: { img: "gems/Gem Type2 Green.png" },
	mmGateDown: { img: "gems/Gem Type2 Purple.png" },
	mmGateTown: { img: "gems/Gem Type2 Blue.png" },
	unvisitedMap: { img: "gui/mapUnvisited.png" },
	invUnmarked: { img: "gui/icons/unmarked.png" },
	invMarked: { img: "gui/icons/marked.png" },
	invAll: { img: "gui/icons/all.png", icon: 'all.png' },
	oreChaff: { img: "ore/oreChaff.png", scale: 0.3, xAnchor: 0.5, yAnchor: 0.5 },
	bloodRed: { img: "dc-misc/bloodRed.png" },
	bloodGreen: { img: "dc-misc/bloodGreen.png" },
	bloodBlue: { img: "dc-misc/bloodBlue.png" },
	bloodYellow: { img: "dc-misc/bloodYellow.png" },
	bloodBlack: { img: "dc-misc/bloodBlack.png" },
	bloodWhite: { img: "dc-misc/bloodYellow.png" },
	glowRed: { img: "effect/glowRed.png" },
	glowGold: { img: "effect/glowGold.png" },
	cloudPoison: { img: "effect/cloudPoison96.png" },
	showImmunity: { img: 'gui/icons/eImmune.png' },
	showResistance: { img: 'gui/icons/eResist.png' },
	showVulnerability: { img: 'gui/icons/eVuln.png' },
	showDodge: { img: 'gui/icons/iDodge.png' },
	showEat: { img: 'gui/icons/activityEat.png' },
	coinSingle: { img: 'item/misc/coinOne.png' },
	eGeneric: { img: "gui/icons/eGeneric.png" },
	ePoof: { img: "gui/icons/ePoof.png" },
	alert: { img: "gui/icons/alert.png" },
	locked: { img: "gui/icons/locked.png" },
	unlock: { img: "gui/icons/unlock.png" },
	open: { img: "gui/icons/open.png" },
	perception: { img: "gui/icons/perception.png" },
	selectBox: { img: "gui/selectBox.png", scale: 1.0, xAnchor: 0, yAnchor: 0 },
	hit: { img: "effect/bolt04.png", scale: 0.4, xAnchor: 0.5, yAnchor: 0.5 },
	// WARNING: This is used very special-case in the ViewMap.
	invisibleObserver: { img: "spells/enchantment/invisibility.png" },
	crosshairYes: { img: "dc-misc/cursor_green.png", scale: 1.0, xAnchor: 0, yAnchor: 0 },
	crosshairNo:  { img: "dc-misc/travel_exclusion.png", scale: 1.0, xAnchor: 0, yAnchor: 0 },
	sortAscending: { img: 'gui/sortAscending.png' },
	sortDescending: { img: 'gui/sortDescending.png' },
	arrowInFlight: { img: 'effect/arrowInFlight.png' },
	dartInFlight: { img: 'effect/dartInFlight.png' },
	slice0: { img: 'gui/sliceEmpty.png' },
	slice10: { img: 'gui/slice10.png' },
	slice20: { img: 'gui/slice20.png' },
	slice30: { img: 'gui/slice30.png' },
	slice40: { img: 'gui/slice40.png' },
	slice50: { img: 'gui/slice50.png' },
	slice60: { img: 'gui/slice60.png' },
	slice70: { img: 'gui/slice70.png' },
	slice80: { img: 'gui/slice80.png' },
	slice90: { img: 'gui/slice90.png' },
	slice100: { img: 'gui/sliceReady.png' },
	// WARNING - these names are direct equivalents to the damage type names, and must align/
	cutIcon: { img: 'gui/icons/damageCut.png' },
	stabIcon:  { img: 'gui/icons/damageStab.png' },
	biteIcon: { img: 'gui/icons/damageBite.png' },
	clawIcon: { img: 'gui/icons/damageClaw.png' },
	bashIcon: { img: 'gui/icons/damageBash.png' },
	burnIcon: { img: 'gui/icons/eBurn.png' },
	lightIcon: { img: 'gui/icons/eLight.png' },
	freezeIcon: { img: 'gui/icons/eFreeze.png' },
	shockIcon: { img: 'gui/icons/eShock.png' },
	corrodeIcon: { img: 'gui/icons/eCorrode.png' },
	poisonIcon: { img: 'gui/icons/ePoison.png' },
	smiteIcon: { img: 'gui/icons/eSmite.png' },
	rotIcon: { img: 'gui/icons/eRot.png' },
	suffocateIcon: { img: 'gui/icons/eSmite.png' },
});

return {
	StickerList: StickerList
}

});
